# Generated by Django 5.2.7 on 2025-10-04 15:09

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('response_time_ms', models.IntegerField(default=0)),
                ('query_classification', models.JSONField(blank=True, default=dict)),
                ('query_enhancement', models.JSONField(blank=True, default=dict)),
                ('intermediate_steps', models.JSONField(blank=True, default=list)),
                ('total_tokens', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, unique=True)),
                ('source_type', models.CharField(choices=[('csv_table', 'CSV Table'), ('pdf_document', 'PDF Document'), ('docx_document', 'DOCX Document'), ('text_document', 'Text Document'), ('vector_store', 'Vector Store')], max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('file_size_kb', models.IntegerField(default=0)),
                ('query_count', models.IntegerField(default=0)),
                ('last_queried_at', models.DateTimeField(blank=True, null=True)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data source stats',
                'ordering': ['source_name'],
            },
        ),
        migrations.CreateModel(
            name='QueryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('query_text', models.TextField()),
                ('query_type', models.CharField(choices=[('structured_sql', 'Structured SQL'), ('semantic_rag', 'Semantic RAG'), ('hybrid', 'Hybrid'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('classification_method', models.CharField(default='keyword', max_length=20)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('sql_used', models.BooleanField(default=False)),
                ('rag_used', models.BooleanField(default=False)),
                ('web_search_used', models.BooleanField(default=False)),
                ('sources_count', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query_type', 'created_at'], name='api_queryan_query_t_531d20_idx'), models.Index(fields=['session_id', 'created_at'], name='api_queryan_session_fe8435_idx')],
            },
        ),
    ]
