# Generated by Django 5.2.7 on 2025-10-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agentinteraction_csvupload_datasourcestats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryanalytics',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queryanalytics',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queryanalytics',
            name='total_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
